config/routes.rb
Rails.application.routes.draw do
  get 'isup/input'

  post 'isup/result'
  get 'isup/result'

  resources :requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # You can have the root of your site routed with "root"
  # root 'welcome#index'
  root 'isup#input', as: 'isup'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/isup_controller.rb
class IsupController < ApplicationController
  
  def input
  end

  def result
     @url_string = params[:url]
    
    if @url_string.nil?
      redirect_to isup_path
      return
    end
    
    if !is_valid_url?(@url_string)
      @status = "URL_Format_Issue"
    else 
      if url_exist?(@url_string)
        @status = "Available"
      else
        @status = "Not_Available"
      end
    end
  
    require 'date'
    current_time = DateTime.now

    request = Request.new
    request.timestamp = current_time.strftime "%d/%m/%Y %H:%M"
    request.url = @url_string
    request.status = @status
    
    request.save
  end
  
  protected
  
  def is_valid_url?(url_str)
    url = url_str
    url.insert(0, "http://") unless(url.match(/^http\:\/\//))
    url =~ /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
  end
  
  require "net/http"
   
  def url_exist?(url_str)
    
    url = url_str
    # check if http:// was in the url if not add it in there
    url.insert(0, "http://") unless(url.match(/^http\:\/\//))
 
    begin
      Timeout::timeout(5) do
        # Get the HTTP_RESPONSE from the site we are checking
        res = Net::HTTP.get_response(URI.parse(url.to_s))
        
        # Check the response code and send an email if the code is bad
        unless(res.code =~ /2|3\d{2}/ ) then
         false
        else
         true
        end
      end   
    rescue Timeout::Error, SocketError
      false
    end
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:url, :timestamp, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/isup_helper.rb
module IsupHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/isup/_format_error_form.html.erb
<div class="format_error">
	</br>
	</br>
	</br>
	<h1>Huh? <%= @url_string %> doesn't look like a site on the interwho.</h1>
	</br>
	<%= link_to 'Try again?', isup_path %>
</div>

app/views/isup/_not_up_form.html.erb
<div class="failure">
	</br>
	</br>
	</br>
	<h1>It's not just you! <%= link_to @url_string, @url_string %> looks down from here.</h1>
	</br>
	<%= link_to 'Check another site?', isup_path %>
</div>

app/views/isup/_up_form.html.erb
<div class="success">
	</br>
	</br>
	</br>
	<h1>It's just you.  <%= link_to @url_string, @url_string %> is up.</h1>
	</br>
	<%= link_to 'Check another site?', isup_path %>
</div>

app/views/isup/input.html.erb
<div id="request_form">
	</br>
	</br>
	</br>
	<%= form_tag(isup_result_path) do %>
	<h1>Is <%= text_field_tag(:url, nil, placeholder: 'google.com') %> down for everyone <%= submit_tag "or is it just me?", :class => "button" %></h1>
	<% end %>
</div>

app/views/isup/result.html.erb
<div class="validate">
	<% if @status == "URL_Format_Issue" %>
		<%= render 'format_error_form' %>
	<% elsif @status == "Available" %>
		<%= render 'up_form' %>
	<% else @status == "Not_Available" %>
		<%= render 'not_up_form' %>
	<% end %>	
	</br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "Down For Everyone Or Just Me?" %></title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="main">
    <%= yield %>
 </div>
</body>
</html>

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :timestamp %>
    <%= f.text_field :timestamp %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Timestamp</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.url %></td>
        <td><%= request.timestamp %></td>
        <td><%= request.status %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @request.url %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @request.timestamp %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>